// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
)

const getDashboard24h = `-- name: GetDashboard24h :one
SELECT
  COUNT(*) FILTER (WHERE event_type='IMAGE_GEN')      AS image_generated,
  COUNT(*) FILTER (WHERE event_type='VIDEO_GEN')      AS video_generated,
  COUNT(*) FILTER (WHERE success)                     AS request_success,
  COUNT(*) FILTER (WHERE NOT success)                 AS request_fail
FROM usage_events
WHERE created_at >= now() - interval '24 hours'
`

type GetDashboard24hRow struct {
	ImageGenerated int64
	VideoGenerated int64
	RequestSuccess int64
	RequestFail    int64
}

// sql 5d1b23a2-1d77-4df1-9c3a-9a1b2c3d4e5f
func (q *Queries) GetDashboard24h(ctx context.Context) (GetDashboard24hRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboard24h)
	var i GetDashboard24hRow
	err := row.Scan(
		&i.ImageGenerated,
		&i.VideoGenerated,
		&i.RequestSuccess,
		&i.RequestFail,
	)
	return i, err
}
