// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Kind               string
	RequestID          uuid.NullUUID
	DerivedFromAssetID uuid.NullUUID
	StorageKey         string
	Mime               string
	Bytes              int64
	Width              sql.NullInt32
	Height             sql.NullInt32
	AspectRatio        sql.NullString
	HashSha256         sql.NullString
	Metadata           json.RawMessage
	CreatedAt          time.Time
}

type ExternalAccount struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ExternalUserID  string
	ClerkExternalID sql.NullString
	Scopes          []string
	AccessToken     sql.NullString
	RefreshToken    sql.NullString
	ExpiresAt       sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type GenerationRequest struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TaskType      string
	Provider      string
	Model         string
	SourceAssetID uuid.NullUUID
	PromptJson    json.RawMessage
	AspectRatio   string
	Quantity      int32
	Status        string
	Progress      int32
	ErrorCode     sql.NullString
	ErrorMessage  sql.NullString
	StartedAt     sql.NullTime
	FinishedAt    sql.NullTime
	CreatedAt     time.Time
}

type PromptTemplate struct {
	ID           uuid.UUID
	UserID       uuid.NullUUID
	Title        string
	Tags         []string
	TemplateJson json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsageEvent struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	RequestID         uuid.NullUUID
	EventType         string
	Success           bool
	LatencyMs         sql.NullInt32
	ProviderCostCents sql.NullInt32
	CreatedAt         time.Time
}

type User struct {
	ID            uuid.UUID
	ClerkUserID   string
	Email         string
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Plan          string
	LocalePref    sql.NullString
	FeatureFlags  json.RawMessage
	LastIpCountry sql.NullString
	LastSeenAt    sql.NullTime
	CreatedAt     time.Time
}

type Watermark struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Type       string
	ConfigJson json.RawMessage
	Active     bool
	CreatedAt  time.Time
}
